### ISSUE TITLE
建议：Bukkit 传送指令以玩家身份执行 BungeeCord 指令

### ISSUE THREAD

**Issue by BingYanchi** [MiniDay/HamsterService-Parent#1]
在 Bukkit 端，让 HamsterService-Bukkit 与 HamsterService-Proxy 沟通，以玩家身份，执行 BungeeCord 指令。

通常运用在 Bukkit 插件想要以玩家身份执行 BungeeCord 指令时。

这是一个很好的点子。

谢谢！

**Comment by MiniDay** [comment]
2.4.1 已添加该功能
